const router = require("express").Router();
const ctrl = require("../controllers/studentController");
const { authenticate, authorize } = require("../middleware/auth");
router.use(authenticate);
router.get("/", ctrl.getAll);
router.get("/:id", ctrl.getById);
router.post("/", authorize("Admin", "Dean"), ctrl.create);
router.put("/:id", authorize("Admin", "Dean"), ctrl.update);
router.delete("/:id", authorize("Admin"), ctrl.remove);
module.exports = router;
